export const movies: any[] = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    year: 1994,
    genre: ["Drama"],
    rating: 9.3,
    director: "Frank Darabont",
    actors: ["Tim Robbins", "Morgan Freeman"],
    plot: "Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.",
    poster: "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
    trailer: "https://www.youtube.com/embed/PLl99DlL6b4",
    runtime: 142,
    awards: "Nominated for 7 Oscars",
    country: "USA",
    language: "English",
    boxOffice: "$28.3 million",
    production: "Columbia Pictures",
    website: "http://www.warnerbros.com/movies/shawshank-redemption",
    "category-label": "top",
  },
  {
    id: 2,
    title: "The Godfather",
    year: 1972,
    genre: ["Crime", "Drama"],
    rating: 9.2,
    director: "Francis Ford Coppola",
    actors: ["Marlon Brando", "Al Pacino", "James Caan"],
    plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    poster: "https://m.media-amazon.com/images/I/51rOnIjLqzL._AC_.jpg",
    trailer: "https://www.youtube.com/embed/sY1S34973zA",
    runtime: 175,
    awards: "Won 3 Oscars",
    country: "USA",
    language: "English",
    boxOffice: "$245.1 million",
    production: "Paramount Pictures",
    website: "https://www.paramountmovies.com/movies/the-godfather",
    "category-label": "popular",
  },
  {
    id: 3,
    title: "The Dark Knight",
    year: 2008,
    genre: ["Action", "Crime", "Drama"],
    rating: 9,
    director: "Christopher Nolan",
    actors: ["Christian Bale", "Heath Ledger", "Gary Oldman"],
    plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    poster: "https://m.media-amazon.com/images/I/91KkWf50SoL._AC_SY679_.jpg",
    trailer: "https://www.youtube.com/embed/EXeTwQWrcwY",
    runtime: 152,
    awards: "Won 2 Oscars",
    country: "USA",
    language: "English",
    boxOffice: "$1.005 billion",
    production: "Warner Bros. Pictures",
    website: "https://www.warnerbros.com/movies/dark-knight",
    "category-label": "playing",
  },
  {
    id: 4,
    title: "Pulp Fiction",
    year: 1994,
    genre: ["Crime", "Drama"],
    rating: 8.9,
    director: "Quentin Tarantino",
    actors: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    plot: "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    poster: "https://m.media-amazon.com/images/I/71c05lTE03L._AC_SY679_.jpg",
    trailer: "https://www.youtube.com/embed/s7EdQ4FqbhY",
    runtime: 154,
    awards: "Won 1 Oscar",
    country: "USA",
    language: "English",
    boxOffice: "$213.9 million",
    production: "Miramax Films",
    website: "https://www.miramax.com/movie/pulp-fiction",
    "category-label": "upcoming",
  },
  {
    id: 6,
    title: "Inception",
    year: 2010,
    genre: ["Action", "Adventure", "Sci-Fi"],
    rating: 8.8,
    director: "Christopher Nolan",
    actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
    plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    poster: "https://m.media-amazon.com/images/I/81p+xe8cbnL._AC_SY679_.jpg",
    trailer: "https://www.youtube.com/embed/8hP9D6kZseM",
    runtime: 148,
    awards: "Won 4 Oscars",
    country: "USA",
    language: "English",
    boxOffice: "$829.9 million",
    production: "Warner Bros. Pictures",
    website: "https://www.warnerbros.com/movies/inception",
    "category-label": "top",
  },
  {
    id: 7,
    title: "The Matrix",
    year: 1999,
    genre: ["Action", "Sci-Fi"],
    rating: 8.7,
    director: "Lana Wachowski, Lilly Wachowski",
    actors: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    plot: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    poster: "https://m.media-amazon.com/images/I/51EG732BV3L._AC_.jpg",
    trailer: "https://www.youtube.com/embed/vKQi3bBA1y8",
    runtime: 136,
    awards: "Won 4 Oscars",
    country: "USA",
    language: "English",
    boxOffice: "$463.5 million",
    production: "Warner Bros. Pictures",
    website: "https://www.warnerbros.com/movies/matrix",
    "category-label": "popular",
  },
  {
    id: 8,
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    genre: ["Adventure", "Drama", "Fantasy"],
    rating: 8.9,
    director: "Peter Jackson",
    actors: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"],
    plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    poster: "https://m.media-amazon.com/images/I/51Qvs9i5a+L._AC_.jpg",
    trailer: "https://www.youtube.com/embed/r5X-hFf6Bwo",
    runtime: 201,
    awards: "Won 11 Oscars",
    country: "USA",
    language: "English",
    boxOffice: "$1.142 billion",
    production: "New Line Cinema",
    website: "https://www.lordoftherings.net/film/the-return-of-the-king",
    "category-label": "playing",
  },
  {
    id: 10,
    title: "Interstellar",
    year: 2014,
    genre: ["Adventure", "Drama", "Sci-Fi"],
    rating: 8.6,
    director: "Christopher Nolan",
    actors: ["Matthew McConaughey", "Anne Hathaway"],
    plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster: "https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SY679_.jpg",
    trailer: "https://www.youtube.com/embed/zSWdZVtXT7E",
    runtime: 169,
    awards: "Won 1 Oscar",
    country: "USA",
    language: "English",
    boxOffice: "$677.5 million",
    production: "Paramount Pictures",
    website: "http://www.paramount.com/movies/interstellar",
    "category-label": "top",
  },
  {
    id: 11,
    title: "Fight Club",
    year: 1999,
    genre: ["Drama"],
    rating: 8.8,
    director: "David Fincher",
    actors: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    plot: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
    poster: "https://m.media-amazon.com/images/I/51v5ZpFyaFL.jpg",
    trailer: "https://www.youtube.com/embed/qtRKdVHc-cE",
    runtime: 139,
    awards: "Nominated for 1 Oscar",
    country: "USA",
    language: "English",
    boxOffice: "$100.9 million",
    production: "20th Century Fox",
    website: "https://www.foxmovies.com/movies/fight-club",
    "category-label": "popular",
  },
  {
    id: 13,
    title: "The Lord of the Rings: The Two Towers",
    year: 2002,
    genre: ["Adventure", "Drama", "Fantasy"],
    rating: 8.7,
    director: "Peter Jackson",
    actors: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
    plot: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
    poster: "https://m.media-amazon.com/images/I/51Qvs9i5a+L._AC_.jpg",
    trailer: "https://www.youtube.com/embed/LbfMDwc4azU",
    runtime: 179,
    awards: "Won 2 Oscars",
    country: "USA",
    language: "English",
    boxOffice: "$951.2 million",
    production: "New Line Cinema",
    website: "https://www.lordoftherings.net/film/the-two-towers",
    "category-label": "upcoming",
  },
  {
    id: 14,
    title: "The Silence of the Lambs",
    year: 1991,
    genre: ["Crime", "Drama", "Thriller"],
    rating: 8.6,
    director: "Jonathan Demme",
    actors: ["Jodie Foster", "Anthony Hopkins", "Lawrence A. Bonney"],
    plot: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    poster: "https://m.media-amazon.com/images/I/51rOnIjLqzL._AC_.jpg",
    trailer: "https://www.youtube.com/embed/W6Mm8Sbe__o",
    runtime: 118,
    awards: "Won 5 Oscars",
    country: "USA",
    language: "English",
    boxOffice: "$272.7 million",
    production: "Orion Pictures",
    website: "https://www.mgm.com/movies/the-silence-of-the-lambs",
    "category-label": "playing",
  },
  {
    id: 18,
    title: "Glory",
    year: 1989,
    genre: ["Drama", "History", "War"],
    rating: 7.8,
    director: "Edward Zwick",
    actors: ["Matthew Broderick", "Denzel Washington", "Cary Elwes"],
    plot: "Robert Gould Shaw leads the U.S. Civil War's first all-black volunteer company, fighting prejudices from both his own Union Army and the Confederates.",
    poster: "https://m.media-amazon.com/images/I/51c6S4kGFmL._AC_.jpg",
    trailer: "https://www.youtube.com/embed/LipejtrhLA0",
    runtime: 122,
    awards: "Won 3 Oscars",
    country: "USA",
    language: "English",
    boxOffice: "$26.8 million",
    production: "TriStar Pictures",
    website: "https://www.sonypictures.com/movies/glory",
    "category-label": "popular",
  },
  {
    id: 19,
    title: "The Avengers",
    year: 2012,
    genre: ["Action", "Adventure", "Sci-Fi"],
    rating: 8,
    director: "Joss Whedon",
    actors: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    poster: "https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SY679_.jpg",
    trailer: "https://www.youtube.com/embed/eOrNdBpGMv8",
    runtime: 143,
    awards: "Nominated for 1 Oscar",
    country: "USA",
    language: "English",
    boxOffice: "$1.518 billion",
    production: "Marvel Studios",
    website: "https://www.marvel.com/movies/the-avengers",
    "category-label": "top",
  },
];
